name: 'SocketChat'
version: 0.0.4
description: 'Server -> Client WebSocket bridge for Bukkit.'

author: NoEff3x
authors: [jacklink01, Colbydude]
website: http://voidteam.net/minecraft/chat

main: net.voidteam.socketchat.SocketChat
database: false
depend: [Essentials, Vault, PExChat]

commands:
  socketchat:
    description: 'Command set used by SocketChat.'
    aliases: [sc, webchat]
    usage: /sc <list|kick|kickall> [username]
  wkick:
    description: 'Kick command for SocketChat.'
    usage: /wkick <username>
  wkickall:
    description: 'Kickall command for SocketChat.'
    usage: /wkickall
